module.exports = {
  content: ['./app/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-high": "#23293c",
        "secondary-container": "#3f465c",
        "surface-container-lowest": "#070d1f",
        "error-container": "#93000a",
        "secondary": "#bec6e0",
        "outline": "#869397",
        "success-emerald": "#10B981",
        "inverse-on-surface": "#2a3043",
        "on-surface": "#dce1fb",
        "tertiary-container": "#ff7f8b",
        "surface-variant": "#2e3447",
        "surface-slate": "#0F172A",
        "primary": "#4cd7f6",
        "on-tertiary-fixed": "#40000d",
        "outline-variant": "#3d494c",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "info-cyan": "#06B6D4",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary": "#003640",
        "on-surface-variant": "#bcc9cd",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-surface": "#dce1fb",
        "surface-bright": "#33394c",
        "on-secondary-fixed": "#131b2e",
        "background": "#0c1324",
        "surface-container": "#191f31",
        "tertiary": "#ffb2b7",
        "secondary-fixed": "#dae2fd",
        "surface-dim": "#0c1324",
        "on-background": "#dce1fb",
        "inverse-primary": "#00687a",
        "error": "#ffb4ab",
        "primary-container": "#06b6d4",
        "primary-fixed-dim": "#4cd7f6",
        "on-tertiary-container": "#7d0023",
        "on-primary-container": "#00424f",
        "surface-tint": "#4cd7f6",
        "primary-fixed": "#acedff",
        "on-primary-fixed-variant": "#004e5c",
        "danger-rose": "#F43F5E",
        "bg-deep": "#020617",
        "surface": "#0c1324",
        "tertiary-fixed": "#ffdadb",
        "on-secondary": "#283044",
        "on-secondary-container": "#adb4ce",
        "on-primary-fixed": "#001f26",
        "on-tertiary": "#67001b",
        "tertiary-fixed-dim": "#ffb2b7",
        "surface-container-highest": "#2e3447",
        "on-tertiary-fixed-variant": "#92002a",
        "surface-container-low": "#151b2d"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "grid-columns": "12",
        "container-max-width": "1440px",
        "gutter": "1.5rem",
        "base-unit": "4px",
        "margin": "2rem"
      },
      "fontFamily": {
        "body-lg": ["Geist"],
        "label-md": ["JetBrains Mono"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Geist"],
        "label-sm": ["JetBrains Mono"]
      },
      "fontSize": {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["10px", {"lineHeight": "12px", "fontWeight": "500"}]
      }
    }
  },
  plugins: [],
}
